### ISSUE TITLE
Add a note about running prettier and eslint at the same time

### ISSUE THREAD

**Issue by Pistrie** [trunk-io/configs#11]
Prettier has a page about integration with other linters, so I'm wondering how Trunk handles this problem. Is there additional setup required?

https://prettier.io/docs/en/integrating-with-linters.html

**Comment by dapirian** [comment]
👋  Hey there, Trunk doesn't handle this problem directly, but we recommend doing exactly what you linked. Just use [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier#installation), it's a 1-liner in your eslint config to add `extends` for `prettier`, which really just turns off all prettier rules in eslint. It speaks to [this guideline](https://github.com/trunk-io/configs#1-turn-off-formatting-errors-use-autoformatters-instead) - no one should want to hear about prettier issues line-by-line via eslint, instead just autoformat the whole file.
